version: '3.3'
services:
  shiny:
    container_name: pheno-ranker-shiny
    image: phenorankerui:${DOCKER_IMG_TAG}
    # build:
    #   context: phenoRankeR/deploy
    #   args:
    #     - IGNORE_CACHE_FROM_HERE=${IGNORE_CACHE_FROM_HERE}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3838:3838
    volumes:
      - shiny-data:/app/data
      - shiny-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      UID: ${UID}
      GID: ${GID}

    restart: unless-stopped
    # healthcheck:
    #   test: curl -f http://0.0.0.0:5000/api/curltest
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    tty: true
    command: ["Rscript", "/app/run_phenoRankeR.R", "dbServer", "db" ]

  db:
    image: postgres:13-alpine
    container_name: pheno-ranker-db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres

volumes:
  postgres-data:
  shiny-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  shiny-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind
