FROM r-base:4.3.3

ENV PPM=packagemanager.posit.co/cran/__linux__/jammy/latest

RUN apt-get update -qq && apt-get -y --no-install-recommends install \
    git \
    gdebi-core \
    imagemagick \
    libfribidi-dev \
    libgit2-dev \
    libharfbuzz-dev \
    libmagick++-dev \
    libssl-dev \
    libtiff-dev \
    libxml2-dev \
    #for PostgreSQL
    odbc-postgresql \
    unixodbc-dev \
    sqlite3 \
    libsqliteodbc

COPY /phenoRankeR ./phenoRankeR

WORKDIR /phenoRankeR

RUN Rscript -e "renv:::renv_pak_init(force = TRUE)"
ENV RENV_CONFIG_PAK_ENABLED=TRUE
RUN Rscript -e "options(repos = c(PPM = 'https://${PPM_URL}')); renv::restore()"

# build package
ENV RENV_CONFIG_PAK_ENABLED=FALSE

WORKDIR /opt
RUN mkdir odbc
RUN { \
    echo "[SQLite]"; \
    echo "Driver = /usr/lib/x86_64-linux-gnu/odbc/libsqlite3odbc.so";  \   
    } >> /opt/odbc/odbcinst.ini

RUN echo "CREATE TABLE test (id INTEGER PRIMARY KEY);" | sqlite3 /opt/test.db

WORKDIR /phenoRankeR
ENV ODBCSYSINI=/opt/odbc
ENV DB_DRIVER=SQLite
ENV DB_NAME=/opt/test.db

RUN mkdir /opt/build
ARG IGNORE_CACHE_FROM_HERE=unknown
RUN echo "IGNORE_CACHE_FROM_HERE=${IGNORE_CACHE_FROM_HERE}"
RUN Rscript -e "devtools::test()" > /opt/build/test.log
RUN Rscript dev/03_deploy.R > /opt/build/build.log

WORKDIR /
RUN cp *.tar.gz /opt/build/.

CMD ["sh"]