proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: keycloak
  admin-groups: shiny
  my-apps-mode: InLine
  server:
    forward-headers-strategy: native
  api-security:
    hide-spec-details: false
  keycloak:
    realm: Shinyproxy
    auth-server-url: http://keycloak:8080/
    ssl-required: external
    resource: shinyproxy
    credentials-secret: GVBBfLDo8RiHSBeSrdoNjRd5SYf97uPz
    admin-groups: shiny
  docker:
    internal-networking: true
  specs:
    - id: 01_phenorankerapp
      display-name: Pheno-Ranker
      description: Pheno-Ranker
      container-cmd:  ["Rscript", "/app/run_phenoRankeR.R", "dbServer", "db" ]
      container-image: phenorankerui:latest
      access-groups: [shiny]
      container-network: pheno-ranker_shiny-net
      container-volumes:
        [
          pheno-ranker_shiny-data:/app/data,
          pheno-ranker_shiny-config:/app/config,
        ]
    - id: 02_hello
      display-name: Hello Application
      description: Application which demonstrates the basics of a Shiny app
      container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      container-image: openanalytics/shinyproxy-demo
      container-network: pheno-ranker_shiny-net
logging:
  file:
    name: shinyproxy.log
