server:
  forward-headers-strategy: native

proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: openid
  my-apps-mode: InLine
  admin-groups: admin
  openid:
    auth-url: "http://${DOMAIN}:8080/realms/${KC_REALM}/protocol/openid-connect/auth"
    # auth-url: "https://${DOMAIN}:8444/auth/realms/${KC_REALM}/protocol/openid-connect/auth"
    logout-url: "http://${DOMAIN}/realms/${KC_REALM}/protocol/openid-connect/logout?client_id=shinyproxy&post_logout_redirect_uri=https://${DOMAIN}"
    token-url: "http://${KC_INTERNAL_URL}/realms/${KC_REALM}/protocol/openid-connect/token"
    jwks-url: "http://${KC_INTERNAL_URL}/realms/${KC_REALM}/protocol/openid-connect/certs"
    client-id: "${KC_CLIENT_ID}"
    Client-secret: "${KC_CLIENT_SECRET}"
    username-attribute: email
    roles-claim: realm_roles
  docker:
    internal-networking: true
    # url: http://host.docker.internal
  specs:
    - id: pheno-ranker
      display-name: Pheno-Ranker
      description: Pheno-Ranker
      container-cmd:
        [
          "Rscript",
          "/app/run_phenoRankeR.R",
          "dbDriver",
          "PostgreSQL",
          "dbServer",
          "db",
          "dbDatabase",
          "${PR_DB_NAME}",
          "dbUser",
          "${PR_DB_USER}",
          "dbPassword",
          "${PR_DB_PW}",
          "dbPort",
          "${PR_DB_PORT}",
        ]
      container-image: "${DOCKER_IMG}"
      access-groups: [admin, user] #assign the role "user" to all users
      # container-network: pheno-ranker-ui_shiny-net
      container-volumes:
        [
          pheno-ranker-ui_shiny-data:/app/data,
          pheno-ranker-ui_shiny-config:/app/config,
        ]
    - id: shinyproxy-demo
      display-name: Shinyproxy demo
      description: Application which demonstrates the basics of a Shiny app
      container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      container-image: openanalytics/shinyproxy-demo
      access-groups: [admin, user] #assign the role "user" to all users
      # container-network: pheno-ranker-ui_shiny-net
logging:
  file:
    name: shinyproxy.log
