name: Docker build

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the image
        run: bash ${GITHUB_WORKSPACE}/build/build_phenoRankeR_w_docker.sh

      - name: push the image
        run: |
          version=$(ls ${GITHUB_WORKSPACE}/phenoRankeR/deploy/*.tar.gz | sed 's/.*_\(.*\)\.tar\.gz/\1/')
          docker tag phenorankerui:${version} ${{ secrets.DOCKERHUB_USERNAME }}/pheno-ranker-ui:${version}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pheno-ranker-ui:${version}
