name: Docker build PhenoRankeR package builder

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the image
        run: docker build -f Dockerfile_package_builder -t phenorankerui-package-builder:latest .

      - name: push the image
        run: |
          docker tag phenorankerui-package-builder:latest ${{ secrets.DOCKERHUB_USERNAME }}/pheno-ranker-ui-r-package-builder:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pheno-ranker-ui-r-package-builder:latest
