---
name: License Compliance Check

on:
  workflow_dispatch:
   
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate License Report
        uses: insightsengineering/r-license-report@v1
        with:
          path: "phenoRankeR"
          #flag non-compliant licenses
          regex: "^AGPL.*"
          # Fail the action if 1 or more matching non-compliant licenses are found
          fail: true
          bioc_release: "3.18"
          as_html: true

      - name: Upload PDF Report
        uses: actions/upload-artifact@v4
        with:
          name: license-report.html
          path: license-report.html