name: R-CMD-check

on:
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    # env:
    #   RENV_CONFIG_PAK_ENABLED: true
    # with above uncommented, the workflow fails with the following error:
    # Error in remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...),

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgit2-dev libsqliteodbc pandoc

      - name: Verify SQLite ODBC Driver installation
        run: |
          sudo find / -name libsqlite3odbc.so
      
      - name: "Check if SQLite ODBC driver are registered"
        run: |
          odbcinst -j
          odbcinst -q -d -n SQLite

      - name: Create custom odbcinst.ini in a user-accessible directory
        run: |
          mkdir -p $HOME/odbc
          echo "[SQLite]" >> $HOME/odbc/odbcinst.ini
          echo "Driver=/usr/lib/x86_64-linux-gnu/odbc/libsqlite3odbc.so" >> $HOME/odbc/odbcinst.ini

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.3"
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          working-directory: phenoRankeR
        env:
          RENV_CONFIG_REPOS_OVERRIDE: ${{ env.RSPM }}

      - name: obdbcListDrivers
        run: |
          cd phenoRankeR
          R -e 'Sys.getenv("ODBCSYSINI")'
          R -e 'odbc::odbcListDrivers()'
        env:
          ODBCSYSINI: /home/runner/odbc

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          working-directory: phenoRankeR
        env:
          ODBCSYSINI: /home/runner/odbc
          DB_DRIVER: SQLite
          DB_NAME: ":memory:"

      # - name: Build package
      #   run: R CMD build phenoRankeR

      # - name: Release package
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: phenoRankeR_*.tar.gz
      #     prerelease: true
