name: release-phenoRankeR

on:
  workflow_dispatch:

jobs:
  release-phenoRankeR:
    runs-on: ubuntu-latest

    # env:
    #   RENV_CONFIG_PAK_ENABLED: true
    # with above uncommented, the workflow fails with the following error:
    # Error in remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...),

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgit2-dev pandoc

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.3"
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          working-directory: phenoRankeR
        env:
          RENV_CONFIG_REPOS_OVERRIDE: ${{ env.RSPM }}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          working-directory: phenoRankeR
      
      - name: Build package
        run: R CMD build phenoRankeR

      - name: Release package
        uses: softprops/action-gh-release@v2
        with:
          files: phenoRankeR_*.tar.gz
          prerelease: true
