name: Snyk docker scan

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Scan phenoRankeR docker image
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: leistivo/pheno-ranker-ui:0.0.0.9006
          args: --file=phenoRankeR/deploy/Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: List all files
        run: ls -l ${{ github.workspace }}

      - name: Upload SARIF to Snyk
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}
